theme = "dracula"

[editor]
line-number = "relative"
mouse = true
rulers = [80]

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[keys.normal]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
